### ISSUE TITLE
Our startup error messages / handling are horrible

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#56]
If you forget to specify a required parameter, all you get is `thread 'main' panicked at 'called`Option::unwrap()`on a`None`value', ../src/libcore/option.rs:323`

We should log something sane, here.

**Comment by skorokithakis** [comment]
I think I fixed this, no?

**Comment by onli** [comment]
I ran into this today. It is not fully fixed.

This is the error message I got: 

    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 
    Store("unable to parse config file")', src/libcore/result.rs:788
    Run with `RUST_BACKTRACE=1` for a backtrace

Of course the backtrace was not very helpful either. My mistakes were: 1) Having http in the link to the (not yet setup) `smtp.server`, and setting allowed `server.allowed_origins` to a string, not  list. It would be good to get told which value could not be parsed.

I also never realized it is possible to just uncomment the config options not needed, like allowed_origins and the google oidc parameters. Is there something preventing us from commenting them out by default?
